[workspace]
members = [
        "doc/calculator",
        "doc/pascal/lalrpop",
        "doc/whitespace",
        "lalrpop-test",
        "lalrpop-docgen",
        "lalrpop-util",
        "lalrpop",
]
